# Generated by Django 5.2.3 on 2025-07-14 01:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0729_externalauthid"),
    ]

    operations = [
        # AIAgentModel: Align to current models/ai_agents.py
        migrations.CreateModel(
            name="AIAgentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("model_type", models.CharField(max_length=20, default="agent")),
                ("context_length", models.IntegerField(default=4096)),
                ("supports_streaming", models.BooleanField(default=True)),
                ("supports_embeddings", models.BooleanField(default=False)),
                ("is_available", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("size_gb", models.FloatField(blank=True, null=True)),
                ("version", models.CharField(blank=True, max_length=50)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "zerver_aiagentmodel",
                "indexes": [
                    models.Index(
                        fields=["is_available", "is_default"], name="zerver_aiag_is_avai_4286ca_idx"
                    ),
                ],
            },
        ),
        # AIAgentConfig: Align to current models (includes default_model and agent_enabled)
        migrations.CreateModel(
            name="AIAgentConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("agent_enabled", models.BooleanField(default=True)),
                ("max_requests_per_user_per_day", models.IntegerField(default=100)),
                ("max_context_length", models.IntegerField(default=4096)),
                ("temperature", models.FloatField(default=0.7)),
                ("top_p", models.FloatField(default=0.9)),
                ("date_created", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "realm",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_agent_config",
                        to="zerver.realm",
                    ),
                ),
                (
                    "default_model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_for_realms",
                        to="zerver.aiagentmodel",
                    ),
                ),
                (
                    "chat_model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_for_realms",
                        to="zerver.aiagentmodel",
                    ),
                ),
                (
                    "embedding_model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="embedding_for_realms",
                        to="zerver.aiagentmodel",
                    ),
                ),
            ],
            options={
                "db_table": "zerver_aiagentconfig",
            },
        ),
        # AIAgentInteraction: Align to current models (no agent_type or token_count fields)
        migrations.CreateModel(
            name="AIAgentInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("prompt", models.TextField()),
                ("response", models.TextField()),
                ("context_type", models.CharField(blank=True, max_length=50)),
                ("context_id", models.IntegerField(blank=True, null=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.aiagentmodel"
                    ),
                ),
            ],
            options={
                "db_table": "zerver_aiagentinteraction",
            },
        ),
        migrations.AddIndex(
            model_name="aiagentinteraction",
            index=models.Index(
                fields=["realm", "user", "timestamp"], name="zerver_aiag_realm_i_884016_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiagentinteraction",
            index=models.Index(
                fields=["success", "timestamp"], name="zerver_aiag_success_75abfd_idx"
            ),
        ),
        # AIAgentUsageStats: Align to current models (includes hour, tokens, response_time_ms)
        migrations.CreateModel(
            name="AIAgentUsageStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("hour", models.IntegerField(default=0)),
                ("prompt_tokens", models.IntegerField(default=0)),
                ("completion_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                ("response_time_ms", models.IntegerField(blank=True, null=True)),
                (
                    "interaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_stats",
                        to="zerver.aiagentinteraction",
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "zerver_aiagentusagestats",
                "unique_together": {("realm", "user", "date", "hour")},
            },
        ),
        migrations.AddIndex(
            model_name="aiagentusagestats",
            index=models.Index(fields=["realm", "date"], name="zerver_aiag_realm_i_d0b6e3_idx"),
        ),
        migrations.AddIndex(
            model_name="aiagentusagestats",
            index=models.Index(fields=["user", "date"], name="zerver_aiag_user_id_83a21c_idx"),
        ),
        # AIAgentAuditLog: Align to current models (no agent_type, keep model_name and configuration_changes)
        migrations.CreateModel(
            name="AIAgentAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("event_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("configuration_changes", models.JSONField(blank=True, default=dict)),
                (
                    "acting_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
            ],
            options={
                "db_table": "zerver_aiagentauditlog",
            },
        ),
        migrations.AddIndex(
            model_name="aiagentauditlog",
            index=models.Index(
                fields=["realm", "event_time"], name="zerver_aiag_realm_i_09c48e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiagentauditlog",
            index=models.Index(
                fields=["event_type", "event_time"], name="zerver_aiag_event_t_b39e68_idx"
            ),
        ),
    ]
